version: "3.9"

services:
  nginx:
    networks:
      - moim-network
    image: qcogns97/moim-nginx:latest
    container_name: moim-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
    restart: always

  backend:
    networks:
      - moim-network
    image: qcogns97/moim-backend:latest
    container_name: moim-backend
    env_file:
      - .env.prod
    expose:
      - "8080"
    depends_on:
      - db
      - redis
    restart: always

  db:
    networks:
      - moim-network
    image: mysql:8.0
    container_name: moim-db
    env_file:
      - .env.prod
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  redis:
    networks:
      - moim-network
    image: redis:7-alpine
    container_name: moim-redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    # 환경 변수를 사용하여 커맨드 구성
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]

  certbot:
    networks:
      - moim-network
    image: certbot/certbot
    container_name: moim-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM;
      while :; do
        certbot renew --webroot -w /var/www/certbot;
        sleep 12h;
      done"

volumes:
  db_data:
  redis_data:

networks:
  moim-network:
    driver: bridge
